services:
  - type: web
    name: smartlearn-backend
    runtime: docker
    rootDir: smartlearn
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
