services:
  - type: web
    name: smartlearn-backend
    runtime: java
    rootDir: smartlearn
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/smartlearn-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JAVA_VERSION
        value: 17