server.port=${PORT:8080}

spring.application.name=smartlearn

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/smartlearn}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
